<?php

return [
    'profile' => 'Perfil',
    'dashboard' => 'Panel de control',
    'add' => 'Agregar',
    'create' => 'Crear',
    'edit' => 'Editar',
    'show' => 'Mostrar',
    'save' => 'Guardar',
    'saved' => 'Guardado',
    'saved_error' => 'Error',
    'filters' => 'Filtros',
    'search' => 'Buscar',
    'reset' => 'Restablecer',
    'total' => 'Total',
    'deleted' => 'Eliminado',
    'delete' => 'Eliminar',
    'deleting' => 'Eliminando',
    'download' => 'Descargar',
    'export' => 'Exportar',
    'import' => 'Importar',
    'cancel' => 'Cancelar',
    'confirm' => 'Confirmar',
    'close' => 'Cerrar',
    'confirm_message' => '¿Estás seguro?',
    'back' => 'Atrás',
    'more' => 'Más',
    'all_sections' => 'Todas las secciones',
    'file' => 'Archivo',
    'loading' => 'Cargando ...',
    'notfound' => 'Registros no encontrados',
    'collapse_menu' => 'Colapsar menú',
    '404' => 'Houston, tenemos un problema: página no encontrada',
    'copied' => '¡Copiado!',
    'notifications' => [
        'title' => 'Notificaciones',
        'mark_as_read_all' => 'Marcar todas como leídas',
        'mark_as_read' => 'Marcar como leído',
    ],
    'login' => [
        'title' => '¡Bienvenido a :moonshine_title!',
        'description' => 'Por favor, inicia sesión en tu cuenta',
        'authorization' => 'Autorización',
        'remember_me' => 'Recuérdame',
        'login' => 'Iniciar sesión',
        'logout' => 'Cerrar sesión',
        'username' => 'Nombre de usuario',
        'email' => 'Correo electrónico',
        'password' => 'Contraseña',
        'or_socials' => 'o',
    ],
    'resource' => [
        'system' => 'Sistema',
        'role' => 'Roles',
        'name' => 'Nombre',
        'email' => 'Correo electrónico',
        'password' => 'Contraseña',
        'repeat_password' => 'Repetir contraseña',
        'avatar' => 'Avatar',
        'created_at' => 'Creado el',
        'admins_title' => 'Administradores',
        'role_title' => 'Roles',
        'role_name' => 'Título',

        'main_information' => 'Información principal',
        'change_password' => 'Cambiar contraseña',

        'link_socialite' => 'Vincular cuenta',
        'linked_socialite' => 'Cuenta vinculada',

        'queued' => 'En cola',

        'export' => [
            'exported' => 'Archivo exportado',
        ],

        'import' => [
            'imported' => 'Importado',
            'file_required' => 'El archivo es obligatorio',
            'extension_not_supported' => 'Extensión de archivo no soportada'
        ]
    ],
    'choices' => [
        'no_results' => 'No se encontraron resultados',
        'no_choices' => 'No hay opciones para elegir',
        'item_select' => 'Presiona para seleccionar',
        'unique_item' => 'Solo se pueden agregar valores únicos',
        'custom_add_item' => 'Solo se pueden agregar valores que cumplan con condiciones específicas',
        'add_item' => 'Presiona Enter para agregar ":value"',
        'max_item' => 'Solo se pueden agregar :count valores',
        'remove_item' => 'Eliminar elemento',
    ],

];
